### ISSUE TITLE
The added value of insulin still exsists after the type of insulin gets removed

### ISSUE THREAD

**Issue by junior291492659** [bvlj/diab#46]
Hi.

- I have searched the history issue list, and have not found a similar bug.

- The bug was found on the latest version 1.3.2 on F-droid, and were reproduciable on a Redmi Note 4X and an Android emulator 6.0 device.

- Bug: select the "Glucose" item, click the floating button, enter a number(e.g. 6), click the "done" icon button and an entry is entered. Click this new entry, click "Add insulin", it shows a toast telling "no insulin found". Then click the "cancle" icon(upper right), select the "Insulin" item to the "insulin" page, click "Add",  input any name(e.g. HelloWorld, skip the input is also fine), click "SAVE". And click "Glucose" to get back to the entry page, click the entry added justnow, click "Add insulin", input any number(e.g. 6, skip the input is also fine so that it will show 0.0), click "APPLY". This entry will be updated with a insulin name as well as a value.

If we go to the "insulin" page and remove the type of insulin added before, return to the "Glucose" page, that entry's value of insulin is not updated(it just lost the name of insulin). Click it to edit, click the remaining value, it just shows a toast telling "no insulin found" of course.

- Reproducing video:
[https://youtu.be/kDu9GYmFPkk](https://youtu.be/kDu9GYmFPkk)

Well, I could totally understand the reason of keeping the value if it comes from your design indeed from the very begining since the value can be restored to be tracked anytime. In a senario where a user want to quit using a type of insulin he added, he can change the default field "extra" to "No longer used" meaning this one is no longer used anymore but keeping the record value is fine. And if he removes the insulin instead, perhaps he really means it and the value is useless, then a dialog asking whether to keep the value would be friendly. 

Anyway, thanks for your useful app. It would be really appreciated to get your concern on this.

**Comment by bvlj** [comment]
Hi, thank you for your report.

I'll be implementing the possibility of removing all the associated values when
deleting an insulin item.

Please keep an eye out for an update coming out in the next weeks.

**Comment by bvlj** [comment]
Fixed with adcfec0

**Comment by junior291492659** [comment]
Hi, Thanks for your quick fix.
